version: '3.4'

services:
    userdb:
        image: mongo
    altamiracachedb:
        image: redis
    api:
        image: ${DOCKER_REGISTRY-}api
        build:
            context: .
            dockerfile: Dockerfile
